version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: grocery_list_postgres_db
    environment:
      POSTGRES_USER: grocery_list_user           # Replace with your desired username
      POSTGRES_PASSWORD: password123   # Replace with your desired password
      POSTGRES_DB: grocery_list_db         # Replace with your desired database name
    ports:
      - "5432:5432"                   # Expose PostgreSQL on the default port 5432
