apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbSecrets.metadataName }}
data:
  postgres-db-user: {{ .Values.dbSecrets.dbUser }}
  postgres-db-password: {{ .Values.dbSecrets.dbPassword }}
  postgres-db-name: {{ .Values.dbSecrets.dbName }}
